@hostname = http://localhost:5000

### Crear una nueva categoría
POST {{hostname}}/api/categorias
Content-Type: application/json

{
  "nombre": "Bebidas"
}

### Obtener todas las categorías
GET {{hostname}}/api/categorias
Accept: application/json
